export type AnimationCategory = "Hero" | "Scroll" | "Interaction" | "Visual" | "Product";

export type Animation = {
  slug: string;
  name: string;
  category: AnimationCategory;
  description: string;
  kind: string;
  size: "medium" | "large";
  level: "Advanced" | "Expert";
  tags: string[];
  library: string;
};

export const categories: Array<"All" | AnimationCategory> = [
  "All",
  "Hero",
  "Scroll",
  "Interaction",
  "Visual",
  "Product",
];

export const animations: Animation[] = [
  { slug: "spatial-ui-assembly", name: "Spatial UI Assembly", category: "Hero", description: "Dashboard layers travel through depth, rotate into place, and settle into one cohesive interface.", kind: "assembly", size: "large", level: "Expert", tags: ["3D", "Interface", "Spring"], library: "Motion + CSS" },
  { slug: "camera-dolly-zoom", name: "Camera Dolly Zoom", category: "Hero", description: "A cinematic push into the product with scale and perspective changing together.", kind: "dolly", size: "large", level: "Expert", tags: ["Perspective", "Camera", "Cinematic"], library: "Motion + CSS" },
  { slug: "portal-transition", name: "Portal Transition", category: "Hero", description: "A small focal point expands into a full composition, turning navigation into a reveal.", kind: "portal", size: "medium", level: "Advanced", tags: ["Mask", "Reveal", "Transition"], library: "Motion" },
  { slug: "liquid-shader-distortion", name: "Liquid Shader Distortion", category: "Visual", description: "A fluid, refractive surface bends the scene with a soft organic pulse. This preview is a CSS starter treatment.", kind: "liquid", size: "large", level: "Expert", tags: ["Fluid", "Shader-inspired", "WebGL"], library: "CSS starter" },
  { slug: "particle-convergence", name: "Particle Convergence", category: "Hero", description: "Scattered points converge into a central mark, suggesting intelligence, synthesis, or an action completing.", kind: "particles", size: "large", level: "Expert", tags: ["Particles", "Canvas", "Brand"], library: "Motion + CSS" },
  { slug: "volumetric-light-sweep", name: "Volumetric Light Sweep", category: "Visual", description: "A focused beam sweeps across layered surfaces and reveals the depth of a product scene.", kind: "light", size: "medium", level: "Advanced", tags: ["Light", "Atmosphere", "Depth"], library: "CSS" },
  { slug: "kinetic-typography", name: "Kinetic Typography", category: "Hero", description: "Type moves with intention—tracking, weight, and position shift to give the brand a distinct voice.", kind: "kinetic", size: "medium", level: "Advanced", tags: ["Type", "Brand", "Motion"], library: "Motion" },
  { slug: "z-axis-choreography", name: "Z-Axis Choreography", category: "Hero", description: "Foreground and background interface layers separate along the depth axis and reconnect in a precise rhythm.", kind: "depth", size: "large", level: "Expert", tags: ["3D", "Depth", "Product"], library: "Motion + CSS" },
  { slug: "procedural-shape-morphing", name: "Procedural Shape Morphing", category: "Visual", description: "An abstract form smoothly changes silhouette, radius, and scale without a hard cut.", kind: "morph", size: "medium", level: "Expert", tags: ["Morph", "Organic", "Loop"], library: "Motion + CSS" },
  { slug: "cinematic-timeline-sequence", name: "Cinematic Timeline Sequence", category: "Hero", description: "Typography, product UI, and ambient details enter as one carefully paced sequence.", kind: "timeline", size: "large", level: "Advanced", tags: ["Timeline", "Sequence", "Hero"], library: "Motion" },
  { slug: "scroll-scrubbed-timeline", name: "Scroll-Scrubbed Timeline", category: "Scroll", description: "The animation is mapped to scroll progress, so visitors can move through the scene at their own pace.", kind: "timeline", size: "large", level: "Expert", tags: ["Scroll", "Scrub", "Storytelling"], library: "Motion" },
  { slug: "pinned-scene-transition", name: "Pinned Scene Transition", category: "Scroll", description: "A section stays in view while its composition evolves through several product states.", kind: "pin", size: "large", level: "Expert", tags: ["Pinned", "Scroll", "Sequence"], library: "GSAP / Motion" },
  { slug: "horizontal-scene-scrubbing", name: "Horizontal Scene Scrubbing", category: "Scroll", description: "Vertical scroll drives a wide horizontal journey through feature panels or product screens.", kind: "horizontal", size: "large", level: "Expert", tags: ["Horizontal", "Scroll", "Story"], library: "GSAP / Motion" },
  { slug: "scroll-driven-camera-flight", name: "Scroll-Driven Camera Flight", category: "Scroll", description: "The scene moves through virtual space as the reader advances down the page.", kind: "dolly", size: "large", level: "Expert", tags: ["Scroll", "Perspective", "3D"], library: "Three.js / Motion" },
  { slug: "progressive-mask-unveiling", name: "Progressive Mask Unveiling", category: "Scroll", description: "A shape or clipping path reveals the next layer of a visual as the story progresses.", kind: "mask", size: "medium", level: "Advanced", tags: ["Mask", "Reveal", "Scroll"], library: "Motion + CSS" },
  { slug: "layered-parallax-depth", name: "Layered Parallax Depth", category: "Scroll", description: "Independent layers move at different rates, producing subtle depth without overwhelming the content.", kind: "parallax", size: "large", level: "Advanced", tags: ["Parallax", "Depth", "Scroll"], library: "Motion" },
  { slug: "scroll-linked-type-deformation", name: "Scroll-Linked Type Deformation", category: "Scroll", description: "Typography stretches, shifts, or changes tracking in response to scroll progress.", kind: "kinetic", size: "medium", level: "Expert", tags: ["Typography", "Scroll", "Variable"], library: "Motion" },
  { slug: "narrative-state-transformation", name: "Narrative State Transformation", category: "Scroll", description: "A single visualization evolves into its next state to explain a product workflow step by step.", kind: "state", size: "large", level: "Advanced", tags: ["Narrative", "State", "Product"], library: "Motion" },
  { slug: "scroll-synchronized-data", name: "Scroll-Synchronized Data Visualization", category: "Scroll", description: "Bars, traces, and figures animate in lockstep with explanatory copy and scroll position.", kind: "chart", size: "large", level: "Advanced", tags: ["Charts", "Scroll", "Metrics"], library: "Motion + SVG" },
  { slug: "continuous-section-morphing", name: "Continuous Section Morphing", category: "Scroll", description: "Backgrounds, masks, and content compositions blend between neighboring sections without a hard reset.", kind: "morph", size: "large", level: "Expert", tags: ["Sections", "Morph", "Transition"], library: "Motion + CSS" },
  { slug: "shared-element-morph", name: "Shared Element Morph Transition", category: "Interaction", description: "The same visual object travels between views while keeping its identity through size and position changes.", kind: "shared", size: "medium", level: "Advanced", tags: ["Layout", "Shared", "Navigation"], library: "Motion" },
  { slug: "flip-layout-animation", name: "FLIP Layout Animation", category: "Interaction", description: "Layout changes are animated from their previous positions into their new positions instead of snapping.", kind: "flip", size: "medium", level: "Advanced", tags: ["Layout", "Reflow", "UI"], library: "Motion" },
  { slug: "spring-physics-interaction", name: "Spring-Physics Interaction", category: "Interaction", description: "Objects respond with tension, momentum, and a controlled settle instead of linear easing.", kind: "spring", size: "medium", level: "Advanced", tags: ["Physics", "Spring", "Gesture"], library: "Motion" },
  { slug: "magnetic-field-interaction", name: "Magnetic Field Interaction", category: "Interaction", description: "Controls subtly gravitate toward the pointer, creating a tactile field around a primary action.", kind: "magnetic", size: "medium", level: "Advanced", tags: ["Cursor", "Button", "Gesture"], library: "Motion" },
  { slug: "inertial-drag-motion", name: "Inertial Drag Motion", category: "Interaction", description: "A draggable object keeps its momentum after release, then eases into a stable resting position.", kind: "drag", size: "medium", level: "Advanced", tags: ["Drag", "Momentum", "Touch"], library: "Motion" },
  { slug: "gesture-driven-3d-tilt", name: "Gesture-Driven 3D Tilt", category: "Interaction", description: "A product or card tilts with pointer movement to create an interactive 3D perspective.", kind: "tilt", size: "medium", level: "Advanced", tags: ["3D", "Pointer", "Card"], library: "Motion + CSS" },
  { slug: "gooey-shape-transition", name: "Gooey Shape Transition", category: "Visual", description: "Soft shapes visually merge and separate like liquid droplets using a gooey filter-inspired treatment.", kind: "gooey", size: "medium", level: "Expert", tags: ["Fluid", "Organic", "SVG"], library: "SVG / CSS" },
  { slug: "morphing-navigation-indicator", name: "Morphing Navigation Indicator", category: "Interaction", description: "An active pill moves between nav items and morphs to match the destination's dimensions.", kind: "nav", size: "medium", level: "Advanced", tags: ["Navigation", "Layout", "Pill"], library: "Motion" },
  { slug: "contextual-expansion-transition", name: "Contextual Expansion Transition", category: "Interaction", description: "A compact control expands into a panel or command surface while preserving visual continuity.", kind: "expand", size: "medium", level: "Advanced", tags: ["Modal", "Context", "Layout"], library: "Motion" },
  { slug: "interruptible-state-transition", name: "Interruptible State Transition", category: "Interaction", description: "A motion sequence changes direction smoothly when the user interacts again before it finishes.", kind: "state", size: "medium", level: "Expert", tags: ["State", "Gesture", "Responsive"], library: "Motion" },
  { slug: "chromatic-aberration-shift", name: "Chromatic Aberration Shift", category: "Visual", description: "Color channels separate around edges for a controlled optical distortion on emphasis or transition.", kind: "chromatic", size: "medium", level: "Expert", tags: ["Optical", "RGB", "Distortion"], library: "CSS starter" },
  { slug: "refraction-glass-shader", name: "Refraction Glass Shader", category: "Visual", description: "A glass-like surface bends the scene behind it. The included starter simulates the treatment with layered blur and highlights.", kind: "glass", size: "medium", level: "Expert", tags: ["Glass", "Refraction", "Shader"], library: "CSS / WebGL" },
  { slug: "dynamic-fresnel-glow", name: "Dynamic Fresnel Glow", category: "Visual", description: "A bright rim intensifies along the edges of a rotating object to suggest reflective depth.", kind: "glow", size: "medium", level: "Expert", tags: ["Rim light", "3D", "Glow"], library: "CSS / Three.js" },
  { slug: "sdf-morphing", name: "SDF Morphing", category: "Visual", description: "Signed-distance-field-style shapes smoothly merge and transform into new silhouettes.", kind: "morph", size: "medium", level: "Expert", tags: ["SDF", "Shader", "Morph"], library: "WebGL starter" },
  { slug: "displacement-map-reveal", name: "Displacement Map Reveal", category: "Visual", description: "A texture displaces pixels during a transition, creating a textured wipe between visual states.", kind: "mask", size: "medium", level: "Expert", tags: ["Texture", "Reveal", "Distortion"], library: "CSS / WebGL" },
  { slug: "dithered-gradient-animation", name: "Dithered Gradient Animation", category: "Visual", description: "A drifting gradient gains fine grain and dither for a tactile, atmospheric surface.", kind: "gradient", size: "medium", level: "Advanced", tags: ["Gradient", "Grain", "Texture"], library: "CSS" },
  { slug: "procedural-wireframe-growth", name: "Procedural Wireframe Growth", category: "Visual", description: "A network of lines grows and connects, building an abstract structure from a few anchor points.", kind: "wireframe", size: "large", level: "Expert", tags: ["Wireframe", "Network", "SVG"], library: "SVG / Canvas" },
  { slug: "metaball-fusion", name: "Metaball Fusion", category: "Visual", description: "Soft forms attract, merge into one silhouette, then separate again with a fluid edge.", kind: "gooey", size: "medium", level: "Expert", tags: ["Metaballs", "Fluid", "SDF"], library: "SVG / WebGL" },
  { slug: "volumetric-particle-field", name: "Volumetric Particle Field", category: "Visual", description: "Particles drift at different depths to create a living atmosphere around the product.", kind: "particles", size: "large", level: "Expert", tags: ["Particles", "Depth", "Ambient"], library: "Canvas / Three.js" },
  { slug: "real-time-environment-reflection", name: "Real-Time Environment Reflection", category: "Visual", description: "Highlights and reflected color shift as a surface or scene changes orientation.", kind: "reflection", size: "medium", level: "Expert", tags: ["Reflection", "Metal", "3D"], library: "Three.js" },
  { slug: "live-data-stream-visualization", name: "Live Data Stream Visualization", category: "Product", description: "Signal lines and data packets flow through a network to make hidden processing feel observable.", kind: "stream", size: "large", level: "Advanced", tags: ["Data", "Pipeline", "Realtime"], library: "SVG / Motion" },
  { slug: "ai-reasoning-trace", name: "AI Reasoning Trace Animation", category: "Product", description: "Processing steps reveal one by one as an AI task moves from intent to tools to result.", kind: "trace", size: "large", level: "Advanced", tags: ["AI", "Steps", "Status"], library: "Motion" },
  { slug: "autonomous-agent-orchestration", name: "Autonomous Agent Orchestration", category: "Product", description: "Multiple agents light up, exchange signals, and hand work across a workflow graph.", kind: "graph", size: "large", level: "Expert", tags: ["Agents", "Graph", "Orchestration"], library: "SVG / Motion" },
  { slug: "reactive-node-graph", name: "Reactive Node Graph", category: "Product", description: "Node states and connecting edges respond to selections, execution states, and graph updates.", kind: "graph", size: "large", level: "Advanced", tags: ["Nodes", "Workflow", "Realtime"], library: "SVG / Motion" },
  { slug: "streaming-token-cascade", name: "Streaming Token Cascade", category: "Product", description: "Words or tokens arrive progressively, turning a response stream into a legible, paced event.", kind: "tokens", size: "medium", level: "Advanced", tags: ["AI", "Streaming", "Text"], library: "Motion" },
  { slug: "command-palette-spatial-transition", name: "Command Palette Spatial Transition", category: "Product", description: "A command surface unfolds from its trigger, then layers search results and contextual actions.", kind: "command", size: "medium", level: "Advanced", tags: ["Command", "Search", "Navigation"], library: "Motion" },
  { slug: "optimistic-ui-reconciliation", name: "Optimistic UI Reconciliation", category: "Product", description: "The interface moves immediately to the expected state, then reconciles smoothly with server truth.", kind: "state", size: "medium", level: "Advanced", tags: ["Optimistic", "Feedback", "State"], library: "Motion" },
  { slug: "animated-state-diff", name: "Animated State Diff", category: "Product", description: "Updated values are highlighted and inserted or removed rows transition instead of appearing abruptly.", kind: "diff", size: "medium", level: "Advanced", tags: ["Data", "Diff", "UI"], library: "Motion" },
  { slug: "real-time-collaborative-presence", name: "Real-Time Collaborative Presence", category: "Product", description: "Remote cursors, selections, and teammate indicators move to communicate shared activity.", kind: "presence", size: "medium", level: "Advanced", tags: ["Collaboration", "Presence", "Realtime"], library: "Motion" },
  { slug: "workflow-execution-pulse", name: "Workflow Execution Pulse", category: "Product", description: "The active node and its connectors pulse as each workflow step progresses through execution states.", kind: "workflow", size: "large", level: "Advanced", tags: ["Workflow", "Execution", "Status"], library: "SVG / Motion" }
];

export function getAnimation(slug: string) {
  return animations.find((animation) => animation.slug === slug);
}
